### ISSUE TITLE
greater_than validator with dynamic value is being ommited

### ISSUE THREAD

**Issue by ajeffika** [DavyJonesLocker/client_side_validations-simple_form#122] opened 2021-06-14 13:11 UTC
When ```:greater_than``` matcher is given in ```validates_numericality``` and the value is taken from model (f.e. column) client side validation doesn't consider it as viable varbiable and ommits this validation

**how to reproduce:**

add validation in your model, on integer :column_name, and add :another_column, also with integer value
```
validates_numericality of :column_name, greater_than_or_equal_to: :another_column_name
```

**What should happen:**

Validation should consider dynamic validation, as does simple form after form submit

**What happens:**

Validator ommits given value, and does not validate the field. If the value in model is specified as:
```
  validates_numericality_of :quantity, greater_than_or_equal_to: 10
```
it works like a charm, however it does not help me in my usecase

### System configuration*
6.0.3.4

**Ruby version**:
2.7.2

**Client Side Validations version**:
15.0

**Client Side Validations Simple Form version**:
13.0.0

### Code snippet from your model of the validations*
```
  validates_numericality_of :quantity, greater_than_or_equal_to: :reserved_quantity
 ```

**Comment by tagliala** [comment] 2021-06-14 13:31
Hi, thanks for being part of the CSV community.

I think this issue should belong to the main CSV repository, but I also think it is a duplicate of DavyJonesLocker/client_side_validations#687

My answer here: https://github.com/DavyJonesLocker/client_side_validations/issues/687#issuecomment-274351991

Closing here, but feel free to comment if I'm wrong

**Closed by tagliala** 2021-06-14 13:31 UTC

**Comment by ajeffika** [comment] 2021-06-14 13:46
Thanks for a fast response!, I've seen that issue, however I was wondering if it still applies when value I'am comparing to is persisted?
